default-shop-account:
  is-free: true
text-color:
  bracket: d
  param: b
  command: f
  error: c
  normal: c
database-type: sqlite
items-db-path: plugins\DynamicMarket\
import-export:
  file: shopDB.csv
  path: plugins\DynamicMarket\
transaction-log:
  file: transactions.log
  autoflush: true
mysql:
  url: jdbc:mysql://localhost/minecraft
  engine: InnoDB
  user: root
  pass: pass
shop-tag: '{BKT}[{}Shop{BKT}]{}'
items-max-per:
  sale: 64
  purchase: 64
debug: false