name: DynamicMarket
main: com.gmail.haloinverse.DynamicMarket.DynamicMarket
version: 0.9 Sentinel
authors: [Klezst, RchGrav, N3X15, Magik, HaloInverse, Nijikokun]
depend: [WorldEdit]
description: >
             A shop plugin building towards an interesting and flexible market system.
commands:
    shop:
       description: Accesses the shop command system.
       usage: |
              /<command>
              /<command> help <topic/command>
              /<command> <itemid>
              /<command> <subcommand> <args>
    dshop:
       description: Accesses the shop command system.
       usage: |
              /<command>
              /<command> help <topic/command>
              /<command> <itemid>
              /<command> <subcommand> <args>