version: 1.0 # Do not change this; it may break updates.
text-color:
  bracket: aqua
  command: light purple
  error: red
  normal: white
  param: gold
database:
  driver: org.sqlite.JDBC
  url: jdbc:sqlite:{DIR}{NAME}.db
  username: root
  password: walrus
  isolation: SERIALIZABLE
  logging: false
import-export-path: plugins\DynamicMarket\ # Location of shops.csv.
transaction-logging: true # Logs transactions in the database table "transactions".