default-shop:
  infinite-funding: true # Shops lose all their money after a restart currently; so, if set to false, it doesn't work as you'd expect.
  items-max-per-transaction: 64
text-color:
  bracket: dark purple
  command: white
  error: red
  normal: gold
  param: aqua
database-type: sqlite
items-db-path: plugins\DynamicMarket\
mysql:
  url: jdbc:mysql://localhost/minecraft
  engine: InnoDB
  user: root
  pass: pass
import-export:
  file: shopDB.csv
  path: plugins\DynamicMarket\
transaction-log:
  file: transactions.log
  autoflush: true
debug: false